settings:
  APP_DISPLAY_NAME: 君聊
  PRODUCTION_APP_NAME: Junchat
  APP_GROUP_IDENTIFIER: group.com.heyujk.junchat
  BASE_BUNDLE_IDENTIFIER: com.heyujk.junchat
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: W834S4TA7S
  JUNCHAT_URL_SCHEME: matrix
  JUNCHAT_ASSOCIATED_DOMAIN: junchat.yyzs120.cn
  JUNCHAT_MATRIX_ACCOUNT_PROVIDER: junchat.yyzs120.cn
  JUNCHAT_OIDC_REDIRECT_URL: https://junchat.yyzs120.cn/oidc/login
  JUNCHAT_PUSH_GATEWAY_BASE_URL: https://sygnal-junchat.yyzs120.cn/junchat-sygnal-v2
  JUNCHAT_PUSH_GATEWAY_NOTIFY_URL: https://sygnal-junchat.yyzs120.cn/_matrix/push/v1/notify?junchat-sygnal=v2&junchat-badge=messages-v1
  JUNCHAT_DIAGNOSTICS_ENDPOINT: https://junchat.yyzs120.cn/junchat-errors/api/v2/uploads
  JUNCHAT_RAGESHAKE_ENABLED: YES
  JUNCHAT_BACKGROUND_APP_REFRESH_TASK_IDENTIFIER: com.heyujk.junchat.background.refresh
